#API open API version
swagger: '2.0'

#this is document metadata
info:
  version: "1.0.0"
  title: Swagger Petstore

host: petstore.swagger.io
basePath: /v2
schemes:
  - https
  - http

tags:
  - name: pet
    description: Everything about your pets

#WEndpoints Requested
paths:
  /pet:

    # first is post
    post:
      tags:
        - pet
      summary: Add a new pet to the store
      consumes:
        0: application/json
        1: application/xml
      produces:
        0: application/json
        1: application/xml
      parameters:
        - name: body
          in: body
          description: Pet object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Pet'
      #query params

      responses:
        405:
          description: Invalid input




definitions:
  Order:
    properties:
      id:
        type: integer
        format: int64
      petId:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int32
      shipDate:
        type: string
        format: date-time
      status:
        type: string
        description: Order Status
        enum:
          0: placed
          1: approved
          2: delivered
      complete:
        type: boolean

  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      userStatus:
        type: integer
        format: int32
        description: User Status

  Category:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Pet:
    type: object
    properties:
      id:
        type: integer
        format: int64
      category:
        $ref: '#/definitions/Category'
        name:
          type: string
          example: doggie
        #formatting needs revision
      photoUrls:
        type: array
        xml:
          name: photoURL
          wrapped: true
        items:
          type: string
          #see https://github.com/swagger-api/swagger-ui/issues/3954
      tags:
        type: array
        xml:
          name: tag
          wrapped: true
        items:
          $ref: '#/definitions/Tag'
      status:
        type: string
        description: pet status in the store
        enum:
          0: available
          1: pending
          2: sold
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string

